# Generated by Django 5.2 on 2025-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('User_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Phone_No', models.IntegerField()),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Show_DateTime', models.DateTimeField()),
                ('No_of_seats', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
